### ISSUE TITLE
Issue with hierarchy.get in README

### ISSUE THREAD

**Issue by joshmoore** [zarr-developers/zarr-java#10]
see: https://github.com/zarr-developers/zarr-java/blob/main/README.md?plain=1#L20

> "Array array = hierarchy.get("color").get("1");" from https://github.com/zarr-developers/zarr-java doesn't appear to be correct. hierarchy.get("color") returns a Node and Node doesn't have a get() method.

cc: @ebremer

**Comment by normanrz** [comment]
It would probably need to a few casts. 
```java
Array array = (Array)((Group)hierarchy.get("color")).get("1");
```

**Comment by dominikl** [comment]
I can't get the README example to run either... even after adding the casts, for the `array.read` call I get:

```
Exception in thread "main" java.lang.RuntimeException: dev.zarr.zarrjava.ZarrException: Error in decoding blosc.
        at dev.zarr.zarrjava.v3.codec.core.ShardingIndexedCodec.lambda$5(ShardingIndexedCodec.java:234)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
...
Caused by: java.lang.RuntimeException: Buffer does not contain valid blosc-encoded contents
        at com.scalableminds.bloscjava.Blosc._decompress(Native Method)
```

Running the `array.write` bit of the code doesn't throw an exception, but I can't see anything written except the zarr.json. But I assume the array data should be written somewhere too, right?
```
> find *
array
array/zarr.json
```
