### ISSUE TITLE
Attempting to write with sharding throws `ArrayIndexOutOfBoundsException`

### ISSUE THREAD

**Issue by melissalinkert** [zarr-developers/zarr-java#5]
I'm in the process of adding sharding options to https://github.com/glencoesoftware/zarr2zarr, but am having a difficult time figuring out how to configure sharding so that chunks can be written without throwing an exception.

A small example, where I'd expect 4 shards total, each containing 4 chunks:

```
FilesystemStore outputStore = new FilesystemStore("tiny-test.zarr");

// 4x4 image
long[] shape = new long[] {4, 4};
// 1x1 chunks == 1 pixel per chunk, expect 16 chunks total
int[] chunkSize = new int[] {1, 1};
// expect 2x2 chunks per shard, 2x2 shards in the image
int[] shardSize = new int[] {2, 2};

Array outputArray = Array.create(outputStore.resolve("0", "0"),
    Array.metadataBuilder()
        .withShape(shape)
        .withDataType(dev.zarr.zarrjava.v3.DataType.UINT8)
        .withChunkShape(chunkSize)
        .withFillValue(255)
        .withCodecs(c -> c.withSharding(shardSize))
        .build()
);

for (int y=0; y<shape[0]; y+=chunkSize[0]) {
    for (int x=0; x<shape[1]; x+=chunkSize[1]) {
        outputArray.write(new long[]{y, x},
            ucar.ma2.Array.factory(ucar.ma2.DataType.UBYTE, chunkSize)
        );
    }
} 
```

If I run that as-is, using zarr-java 0.0.2, it throws an exception during array writing:

```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException
	at ucar.ma2.Index3D.set0(Index3D.java:86)
	at ucar.ma2.Index3D.set(Index3D.java:115)
	at dev.zarr.zarrjava.v3.codec.core.ShardingIndexedCodec.setValueFromShardIndexArray(ShardingIndexedCodec.java:92)
	at dev.zarr.zarrjava.v3.codec.core.ShardingIndexedCodec.lambda$encode$1(ShardingIndexedCodec.java:141)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:408)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:736)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:661)
	at dev.zarr.zarrjava.v3.codec.core.ShardingIndexedCodec.encode(ShardingIndexedCodec.java:116)
	at dev.zarr.zarrjava.v3.codec.CodecPipeline.encode(CodecPipeline.java:145)
	at dev.zarr.zarrjava.v3.Array.writeChunk(Array.java:301)
	at dev.zarr.zarrjava.v3.Array.lambda$write$1(Array.java:279)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at dev.zarr.zarrjava.v3.Array.write(Array.java:257)
```

If I replace `int[] shardSize = new int[] {2, 2};` with `int[] shardSize = new int[] {1, 1};` in the test code, though, then there is no exception and I get the expected output, which is one shard == one chunk. I don't know if this is an issue with zarr-java, or if I'm just misunderstanding something and need to fix the test code - either way, any ideas would be much appreciated.

**Comment by normanrz** [comment]
I think chunkSize and shardSize need to be used in reverse order:
```java
FilesystemStore outputStore = new FilesystemStore("tiny-test.zarr");

// 4x4 image
long[] shape = new long[] {4, 4};
// 1x1 chunks == 1 pixel per chunk, expect 16 chunks total
int[] chunkSize = new int[] {1, 1};
// expect 2x2 chunks per shard, 2x2 shards in the image
int[] shardSize = new int[] {2, 2};

Array outputArray = Array.create(outputStore.resolve("0", "0"),
    Array.metadataBuilder()
        .withShape(shape)
        .withDataType(dev.zarr.zarrjava.v3.DataType.UINT8)
        .withChunkShape(shardSize)
        .withFillValue(255)
        .withCodecs(c -> c.withSharding(chunkSize))
        .build()
);

for (int y=0; y<shape[0]; y+=chunkSize[0]) {
    for (int x=0; x<shape[1]; x+=chunkSize[1]) {
        outputArray.write(new long[]{y, x},
            ucar.ma2.Array.factory(ucar.ma2.DataType.UBYTE, chunkSize)
        );
    }
}
```

We modeled this after the zarr spec, where shards are considered chunks from the Array perspective. Sub chunks are then chunks of a shard. This could be nested even further, although, I haven't found a use case for that yet.

We can discuss, whether we want to change this for the Java library. In any case the library should validate that chunkSize and shardSize are compatible.

**Comment by melissalinkert** [comment]
Thank you @normanrz, that's really helpful.

> In any case the library should validate that chunkSize and shardSize are compatible.

We can certainly check that in zarr2zarr in the meantime. If the shard size is an exact multiple of the chunk size, is that sufficient? Or does the array shape need to be compared with the shard and/or chunk size as well?

**Comment by normanrz** [comment]
> If the shard size is an exact multiple of the chunk size, is that sufficient?

Yes, that should be sufficient.
